# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'
platform :ios, '15.6'

inhibit_all_warnings!
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false

target 'VXWalkthrough' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VXWalkthrough
  pod 'QRCodeReader.swift'
end

post_install do |installer|
	installer.generated_projects.each do |project|
		project.targets.each do |target|
			target.build_configurations.each do |config|
				config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
			end
		end
	end
end
